// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfOcbkcE5NnVyDR7n0yJsBsHNHaBYb1Z8',
    appId: '1:848009703051:web:f680a60e859a655283ee8e',
    messagingSenderId: '848009703051',
    projectId: 'be-safe-dcd9b',
    authDomain: 'be-safe-dcd9b.firebaseapp.com',
    storageBucket: 'be-safe-dcd9b.appspot.com',
    measurementId: 'G-HE1SYGW0Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeqMlwKXN649s9Ro2TnNwuA9SM8BmtduQ',
    appId: '1:848009703051:android:2438c0aee8ab111483ee8e',
    messagingSenderId: '848009703051',
    projectId: 'be-safe-dcd9b',
    storageBucket: 'be-safe-dcd9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlXlP7KdvhrG-tJpkacyq7jGkcC8Ec43U',
    appId: '1:848009703051:ios:eb0912d19248dea083ee8e',
    messagingSenderId: '848009703051',
    projectId: 'be-safe-dcd9b',
    storageBucket: 'be-safe-dcd9b.appspot.com',
    iosClientId: '848009703051-lu61jnnfgdlmtujoridf01km62h15qur.apps.googleusercontent.com',
    iosBundleId: 'com.example.beSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlXlP7KdvhrG-tJpkacyq7jGkcC8Ec43U',
    appId: '1:848009703051:ios:eb0912d19248dea083ee8e',
    messagingSenderId: '848009703051',
    projectId: 'be-safe-dcd9b',
    storageBucket: 'be-safe-dcd9b.appspot.com',
    iosClientId: '848009703051-lu61jnnfgdlmtujoridf01km62h15qur.apps.googleusercontent.com',
    iosBundleId: 'com.example.beSafe',
  );
}
